version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - pip install --upgrade pip
            - pip install -r requirements.txt
            - echo "Running all unit tests"
    pre_build:
        commands:
           - echo "Running all unit tests"
    build:
        commands:  
            - echo "Running all unit tests"
artifacts:
    files:
        - '**/*'