# Generated by Django 3.2.7 on 2022-04-13 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='new_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=100)),
                ('job_salary', models.IntegerField()),
                ('job_company', models.CharField(max_length=100)),
                ('job_contact', models.CharField(max_length=100)),
                ('job_email', models.EmailField(max_length=254)),
                ('job_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.IntegerField()),
                ('candidate_location', models.CharField(max_length=100)),
                ('candidate_experience', models.CharField(max_length=100)),
                ('candidate_resume', models.FileField(upload_to='resume/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL)),
                ('candidate_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_job', to='project.new_job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
