# Generated by Django 3.2.7 on 2022-04-13 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate',
            new_name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_job',
        ),
        migrations.RemoveField(
            model_name='new_job',
            name='employee',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='applied_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='project.candidate')),
                ('new_job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_job', to='project.new_job')),
            ],
        ),
        migrations.AddField(
            model_name='new_job',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='project.employee'),
            preserve_default=False,
        ),
    ]
