# Generated by Django 3.2.7 on 2022-04-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20220413_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_job',
            name='job_time',
        ),
    ]
