# Generated by Django 3.2.7 on 2022-04-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_new_job_job_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_job',
            name='job_image',
            field=models.ImageField(blank=True, upload_to='JOBimages'),
        ),
    ]
