# Generated by Django 3.2.7 on 2022-04-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_new_job_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new_job',
            name='job_salary',
            field=models.PositiveIntegerField(),
        ),
    ]
